### ISSUE TITLE
how to use sparglim-server to connect hive metastore

### ISSUE THREAD

**Issue by jixianyihao** [Wh1isper/sparglim#14]
how to use sparglim-server to connect hive metastore?

### Problem

I use the sparglim-server, started with hive config, but it only can connect hdfs, not use hive metestore.

at the same time, we sparglim on k8s, it's ok

### Proposed Solution
how to config sparglim to make hive metasore? spark.sql(select * from stg.xxx).show()?

**Comment by Wh1isper** [comment]
Thanks for your feedback, `sparglim-server` wraps the spark connect server into an easy to configure daemon. It was originally intended to make `spark connect server` easy to run on k8s.

According to the official documentation of spark, https://spark.apache.org/docs/latest/configuration.html#custom-hadoophive-configuration, you can use `spark.hadoop.*` as well as `spark. hive.*` to configure hadoop/hive.

Sparglim [supports the use of environment variables to configure certain properties](https://github.com/Wh1isper/sparglim/blob/main/config.md), **but unfortunately the above settings are not yet supported**. So, for now, you may have to rebuild the image on top of the existing one by placing hdfs-site.xml, core-site.xml, yarn-site.xml, hive-site.xml, etc. under the Spark classpath, or by placing the configurations in `$SPARK_HOME/conf/spark-defaults.conf`.

Perhaps we should consider having `sparglim-server` accept custom configurations, given that `sparglim-server` can't programmatically modify the configuration like `ConfigBuilder.config`.

**Comment by Wh1isper** [comment]
> Perhaps we should consider having `sparglim-server` accept custom configurations, given that `sparglim-server` can't programmatically modify the configuration like `ConfigBuilder.config`.

I just added a support for json string custom properties, posted in version 0.2.0.

Please pull the latest image and configure the environment variable: `SPARGLIM_SERVER_CUSTOM_CONFIG`: https://github.com/Wh1isper/sparglim/blob/0.2.0/examples/sparglim-server/k8s/deployment.yaml#L36

Alternatively, you can go into the pod of `sparglim-server` and find the log under `/opt/spark/work-dir/logs`, which will tell the startup command at the very beginning. This can help you confirm that the configuration is in effect.

> ![image](https://github.com/Wh1isper/sparglim/assets/43375501/9913a97b-7a06-4c8d-bab7-42eabc16e79b)
> When I assign SPARGLIM_SERVER_CUSTOM_CONFIG='{"a": "b"}'

**Comment by jixianyihao** [comment]
thx,  below is configuration
```
'logs/spark-sparglim-connect-server-org.apache.spark.sql.connect.service.SparkConnectServer-1-sparglim-server-86dc94c545-mbq5n.out']
Spark Command: /opt/java/openjdk/bin/java -cp /opt/spark/conf/:/opt/spark/jars/* -Xmx1g -XX:+IgnoreUnrecognizedVMOptions --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/sun.nio.cs=ALL-UNNAMED --add-opens=java.base/sun.security.action=ALL-UNNAMED --add-opens=java.base/sun.util.calendar=ALL-UNNAMED --add-opens=java.security.jgss/sun.security.krb5=ALL-UNNAMED -Djdk.reflect.useDirectMethodHandle=false org.apache.spark.deploy.SparkSubmit --conf spark.kubernetes.container.image.pullPolicy=IfNotPresent --conf spark.executor.memory=512m --conf spark.master=k8s://https://192.167.0.1:443 --conf spark.driver.extraLibraryPath=/opt/hadoopclient//Spark2x/spark/native --conf spark.kubernetes.authenticate.oauthTokenFile=/var/run/secrets/kubernetes.io/serviceaccount/token --conf spark.executor.extraLibraryPath=/opt/hadoopclient//Spark2x/spark/native --conf spark.kubernetes.executor.annotation.sparglim-executor=true --conf spark.app.name=Sparglim --conf spark.kubernetes.kerberos.krb5.configMapName=krb5-config --conf spark.submit.deployMode=client --conf spark.driver.bindAddress=0.0.0.0 --conf spark.driver.host=192.168.19.8 --conf spark.kubernetes.namespace=spark --conf spark.kubernetes.container.image=idm.dfsx.com/library/spark-executor:0.2-test --conf spark.scheduler.mode=FAIR --conf spark.kerberos.keytab=/opt/a5oldkeytab/user.keytab --conf spark.kubernetes.driver.pod.name=sparglim-server-86dc94c545-mbq5n --conf spark.executor.instances=3 --conf spark.kerberos.principal=xcydsdfs@HADOOP.COM --conf spark.kubernetes.hadoop.configMapName=sparkconfig --conf spark.kerberos.access.hadoopFileSystems=hdfs://ns01,hdfs://nsfed,hdfs://hacluster --conf spark.kubernetes.executor.label.sparglim-executor=true --conf spark.kubernetes.authenticate.caCertFile=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt --conf spark.sql.warehouse.dir=hdfs://hacluster/user/hive/warehouse --class org.apache.spark.sql.connect.service.SparkConnectServer --name Spark Connect server spark-internal
``` 
but it does not try to connect hivemetastore, 

error msg:
```
23/12/22 18:07:07 INFO HadoopDelegationTokenManager: Attempting to login to KDC using principal: xcydsdfs@HADOOP.COM
23/12/22 18:07:07 INFO HadoopDelegationTokenManager: Successfully logged into KDC.

23/12/22 18:07:10 INFO HiveConf: Found configuration file file:/opt/spark/conf/hive-site.xml
23/12/22 18:07:10 WARN HiveConf: HiveConf of name hive.security.acl.flag does not exist
23/12/22 18:07:10 WARN HiveConf: HiveConf of name hive.http.filter.initializers does not exist
23/12/22 18:07:10 WARN HiveConf: HiveConf of name hive.metastore.million.partition.optimizer.batch.retrieve.max does not exist
23/12/22 18:07:10 WARN HiveConf: HiveConf of name hive.session.tenant.assignment.name.service.enabled does not exist
23/12/22 18:07:10 WARN HiveConf: HiveConf of name hive.hadoop.supports.splittable.combineinputformat does not exist
23/12/22 18:07:10 WARN HiveConf: HiveConf of name hive.metastore.million.partition.optimizer.batch.delete.max does not exist
23/12/22 18:07:10 WARN HiveConf: HiveConf of name hive.metastore.thrift.sasl.qop does not exist
23/12/22 18:07:10 WARN HiveConf: HiveConf of name hive.warehouse.multiple.tenant.enabled does not exist
23/12/22 18:07:10 WARN HiveConf: HiveConf of name hive.metastore.db.ssl.enabled does not exist
23/12/22 18:07:10 WARN HiveConf: HiveConf of name hive.sql.log.enable does not exist
23/12/22 18:07:10 WARN HiveConf: HiveConf of name hive.sparktez.lib.check.interval does not exist
23/12/22 18:07:10 WARN HiveConf: HiveConf of name hive.msck.threadpool.size does not exist
23/12/22 18:07:10 INFO HadoopDelegationTokenManager: Calculated delay on renewal is 64798511, based on next renewal 1703326028451 and the ratio 0.75, and current time 1703239630436
23/12/22 18:07:10 INFO HadoopDelegationTokenManager: Scheduling renewal in 18.0 h.
23/12/22 18:07:10 INFO HadoopDelegationTokenManager: Updating delegation tokens.
23/12/22 18:07:10 INFO SparkHadoopUtil: Updating delegation tokens for current user.
23/12/22 18:07:10 INFO SparkHadoopUtil: Updating delegation tokens for current user.

23/12/22 18:07:10 INFO ExecutorPodsAllocator: Going to request 3 executors from Kubernetes for ResourceProfile Id: 0, target: 3, known: 0, sharedSlotFromPendingPods: 2147483647.
23/12/22 18:07:10 INFO ExecutorPodsAllocator: Found 0 reusable PVCs from 0 PVCs
23/12/22 18:07:10 INFO KubernetesClientUtils: Spark configuration files loaded from Some(/opt/spark/conf) : core-site.xml,hdfs-site.xml,hive-site.xml,hivemetastore-site.xml
23/12/22 18:07:10 INFO KubernetesClientUtils: Spark configuration files loaded from Some(/opt/spark/conf) : core-site.xml,hdfs-site.xml,hive-site.xml,hivemetastore-site.xml
23/12/22 18:07:10 INFO BasicExecutorFeatureStep: Decommissioning not enabled, skipping shutdown script
23/12/22 18:07:10 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 46493.
23/12/22 18:07:10 INFO NettyBlockTransferService: Server created on 192.168.19.8 0.0.0.0:46493
23/12/22 18:07:10 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
23/12/22 18:07:10 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 192.168.19.8, 46493, None)
23/12/22 18:07:10 INFO BlockManagerMasterEndpoint: Registering block manager 192.168.19.8:46493 with 434.4 MiB RAM, BlockManagerId(driver, 192.168.19.8, 46493, None)
23/12/22 18:07:10 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 192.168.19.8, 46493, None)
23/12/22 18:07:10 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 192.168.19.8, 46493, None)
23/12/22 18:07:11 INFO KubernetesClientUtils: Spark configuration files loaded from Some(/opt/spark/conf) : core-site.xml,hdfs-site.xml,hive-site.xml,hivemetastore-site.xml
23/12/22 18:07:11 INFO BasicExecutorFeatureStep: Decommissioning not enabled, skipping shutdown script
23/12/22 18:07:11 INFO KubernetesClientUtils: Spark configuration files loaded from Some(/opt/spark/conf) : core-site.xml,hdfs-site.xml,hive-site.xml,hivemetastore-site.xml
23/12/22 18:07:11 INFO BasicExecutorFeatureStep: Decommissioning not enabled, skipping shutdown script
23/12/22 18:07:15 INFO KubernetesClusterSchedulerBackend$KubernetesDriverEndpoint: No executor found for 192.168.241.98:58554
23/12/22 18:07:15 INFO KubernetesClusterSchedulerBackend$KubernetesDriverEndpoint: No executor found for 192.168.85.236:54970
23/12/22 18:07:15 INFO KubernetesClusterSchedulerBackend$KubernetesDriverEndpoint: No executor found for 192.168.16.250:45664
23/12/22 18:07:15 INFO KubernetesClusterSchedulerBackend$KubernetesDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (192.168.241.98:58556) with ID 1,  ResourceProfileId 0
23/12/22 18:07:15 INFO BlockManagerMasterEndpoint: Registering block manager 192.168.241.98:35017 with 117.0 MiB RAM, BlockManagerId(1, 192.168.241.98, 35017, None)
23/12/22 18:07:15 INFO KubernetesClusterSchedulerBackend$KubernetesDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (192.168.85.236:54982) with ID 2,  ResourceProfileId 0
23/12/22 18:07:15 INFO BlockManagerMasterEndpoint: Registering block manager 192.168.85.236:43737 with 117.0 MiB RAM, BlockManagerId(2, 192.168.85.236, 43737, None)
23/12/22 18:07:16 INFO KubernetesClusterSchedulerBackend$KubernetesDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (192.168.16.250:45670) with ID 3,  ResourceProfileId 0
23/12/22 18:07:16 INFO KubernetesClusterSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.8
23/12/22 18:07:16 INFO BlockManagerMasterEndpoint: Registering block manager 192.168.16.250:38393 with 117.0 MiB RAM, BlockManagerId(3, 192.168.16.250, 38393, None)
23/12/22 18:07:16 INFO SparkConnectServer: Spark Connect server started.
23/12/22 18:10:08 INFO SharedState: Setting hive.metastore.warehouse.dir ('/user/hive/warehouse') to the value of spark.sql.warehouse.dir.
23/12/22 18:10:08 INFO SharedState: Warehouse path is 'hdfs://hacluster/user/hive/warehouse'.
23/12/22 18:10:10 WARN Client: Exception encountered while connecting to the server 

``` 
when I use spark-submit to submit job, it will have such logs:
```
23/12/23 01:43:52 INFO HiveUtils: Initializing HiveMetastoreConnection version 2.3.9 using Spark classes.

```
but start-connect-server dont have this logs

**Comment by Wh1isper** [comment]
> According to the official documentation of spark, [spark.apache.org/docs/latest/configuration.html#custom-hadoophive-configuration](https://spark.apache.org/docs/latest/configuration.html#custom-hadoophive-configuration), you can use spark.hadoop.* as well as spark.hive.* to configure hadoop/hive.

Please refer to the official documentation for configuration.

> 23/12/22 18:07:10 INFO HiveConf: Found configuration file file:/opt/spark/conf/hive-site.xml

It looks like you have `hive` related files on your **local machine** when using spark-submit. However, when `sparglim-server` is running in a container, it cannot fetch this file. That's why I suggested above that you package the relevant files into an image, or mount them.

> 'logs/spark-sparglim-connect-server-org.apache.spark.sql.connect.service.SparkConnectServer-1-sparglim-server-86dc94c545-mbq5n.out']
Spark Command: /opt/java/openjdk/bin/java -cp /opt/spark/conf/:/opt/spark/jars/* -Xmx1g -XX:+IgnoreUnrecognizedVMOptions --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/sun.nio.cs=ALL-UNNAMED --add-opens=java.base/sun.security.action=ALL-UNNAMED --add-opens=java.base/sun.util.calendar=ALL-UNNAMED --add-opens=java.security.jgss/sun.security.krb5=ALL-UNNAMED -Djdk.reflect.useDirectMethodHandle=false org.apache.spark.deploy.SparkSubmit --conf spark.kubernetes.container.image.pullPolicy=IfNotPresent --conf spark.executor.memory=512m --conf spark.master=k8s://https://192.167.0.1:443 --conf spark.driver.extraLibraryPath=/opt/hadoopclient//Spark2x/spark/native --conf spark.kubernetes.authenticate.oauthTokenFile=/var/run/secrets/kubernetes.io/serviceaccount/token --conf spark.executor.extraLibraryPath=/opt/hadoopclient//Spark2x/spark/native --conf spark.kubernetes.executor.annotation.sparglim-executor=true --conf spark.app.name=Sparglim --conf spark.kubernetes.kerberos.krb5.configMapName=krb5-config --conf spark.submit.deployMode=client --conf spark.driver.bindAddress=0.0.0.0 --conf spark.driver.host=192.168.19.8 --conf spark.kubernetes.namespace=spark --conf spark.kubernetes.container.image=idm.dfsx.com/library/spark-executor:0.2-test --conf spark.scheduler.mode=FAIR --conf spark.kerberos.keytab=/opt/a5oldkeytab/user.keytab --conf spark.kubernetes.driver.pod.name=sparglim-server-86dc94c545-mbq5n --conf spark.executor.instances=3 --conf spark.kerberos.principal=xcydsdfs@HADOOP.COM --conf spark.kubernetes.hadoop.configMapName=sparkconfig --conf spark.kerberos.access.hadoopFileSystems=hdfs://ns01,hdfs://nsfed,hdfs://hacluster --conf spark.kubernetes.executor.label.sparglim-executor=true --conf spark.kubernetes.authenticate.caCertFile=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt --conf spark.sql.warehouse.dir=hdfs://hacluster/user/hive/warehouse --class org.apache.spark.sql.connect.service.SparkConnectServer --name Spark Connect server spark-internal

I don't see `spark.hive-*` related in the spark-connect-server startup command, According to the official recommendations, using spark properties to config hive, you can do the following configuration.

1. Convert the contents of your `/opt/spark/conf/hive-site.xml` file to a json string
2. Assign environment variable `SPARGLIM_SERVER_CUSTOM_CONFIG`={the-json-string}

**Comment by Wh1isper** [comment]
Also, since Spark on k8s starts multiple executor pods and the **actual data reads happen on the executor pod**, I'm not sure if you're configuring this file to take effect only on the master's pod (`sparglim-server`), as well as you can get the executor's logs to see if there are any logs for `HiveMetastoreConnection`.

**Comment by jixianyihao** [comment]
thank you, After check again, I found, start-connect-server.sh 的main Class， SparkConnectServer， it create first sparkSession without hive support, after I change  
![image](https://github.com/Wh1isper/sparglim/assets/15052159/ea1aa601-1523-44ec-80d7-3827dcf40b9e)

with enableHiveSupport， when damon server start， It will use hiveclient to connect hive metastore.


Thank you to provide this great  project.

**Comment by Wh1isper** [comment]
Great! Feel free to provide more feedback. :D

>  it create first sparkSession without hive support

This sounds like a mistake by Spark, perhaps you could raise an issue to Spark.
